name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Checka ut koden
      - name: Check out code
        uses: actions/checkout@v2

      # Steg 2: Installera Python (anpassa om du använder ett annat språk)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Steg 3: Installera dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Steg 4: Kör tester
      - name: Run tests
        run: |
          pytest
